### ISSUE TITLE
Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.26.0'`

### ISSUE THREAD

**Issue by Chefstephano** [kijai/ComfyUI-Florence2#106]
This is for a BUMP. I've read the previous issues on this error. I've tried:
Reinstalling ComfyUI from scratch
Reinstalling Custom Nodes from scratch
Updating drivers
Uninstalling old Python versions
Downgrading my CUDA back to 11.4 because I had updated it earlier
Restarting the computer several times
And other things

accelerate>=0.26.0 is already already in the node 'requirements.txt'
The Florence model is installed, it downloaded successfully previously.

I've never needed to use 'low_cpu_mem_usage' before, having previously run other flux models. I don't even know where to find it to disable it. 

The error:

> 2024-12-23T21:20:41.358652 - got prompt
2024-12-23T21:20:41.613461 - using sdpa for attention2024-12-23T21:20:41.613461 - 
2024-12-23T21:20:41.647491 - No flash_attn import to remove2024-12-23T21:20:41.647491 - 
2024-12-23T21:20:41.660503 - !!! Exception during processing !!! Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.26.0'`
2024-12-23T21:20:41.664507 - Traceback (most recent call last):
  File "A:\dying drive\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\dying drive\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\dying drive\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "A:\dying drive\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\dying drive\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 99, in loadmodel
    model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation=attention, device_map=device, torch_dtype=dtype,trust_remote_code=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\dying drive\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 559, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\dying drive\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 3589, in from_pretrained
    raise ImportError(
ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.26.0'`

**Comment by Chefstephano** [comment]
I worked this problem for about 16 hours, don't know what fixed it. Fresh ComfyUI (which I did 6 times prior), and ran "update_comfyui_and_python_dependencies.bat" inside the "update" folder after reinstalling python and CUDA and torch.

I also tried running a git-clone version of comfyui inside an anaconda environment to check to see if python, CUDA, and torch had compatibility problems but that output the exact same error, so....

Anyways, problem solved, sorry I can't offer a proper solution.
