### ISSUE TITLE
pip install -r requirements.txt ?

### ISSUE THREAD

**Issue by lunatico67** [kijai/ComfyUI-Florence2#55]
Hi
In which folder should I apply pip install -r requirements.txt ?
In C:\Users\------\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2 ?
or
In C:\Users\-----\Documents\ComfyUI_windows_portable\python_embeded\python.exe ?

**Comment by kijai** [comment]
In your C:\Users------\Documents\ComfyUI_windows_portable:
`python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI-Florence2\requirements.txt`

**Comment by lunatico67** [comment]
> In your C:\Users------\Documents\ComfyUI_windows_portable: `python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI-Florence2\requirements.txt`

Thanks for the help. I have installed it and when I open comfyui in the console I get this error:

[ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
Traceback (most recent call last):
  File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\server.py", line 447, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\server.py", line 424, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 141, in INPUT_TYPES
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()],),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 141, in <listcomp>
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()],),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 931, in iterdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\luna\\Documents\\ComfyUI_windows_portable\\ComfyUI\\models\\LLM'

**Comment by kijai** [comment]
> > In your C:\Users------\Documents\ComfyUI_windows_portable: `python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI-Florence2\requirements.txt`
> 
> Thanks for the help. I have installed it and when I open comfyui in the console I get this error:
> 
> [ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node. Traceback (most recent call last): File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\server.py", line 447, in get_object_info out[x] = node_info(x) ^^^^^^^^^^^^ File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\server.py", line 424, in node_info info['input'] = obj_class.INPUT_TYPES() ^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 141, in INPUT_TYPES "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()],), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 141, in "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()],), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "pathlib.py", line 931, in iterdir FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\models\LLM'

You can use the other model loader to autodownload the models, that one you now tried to use requires putting Florence2 models to the ComfyUI/models/LLM -folder.

**Comment by lunatico67** [comment]
Thank you very much, I will do so
