### ISSUE TITLE
when choosing Florence-2-base-PromptGen-v1.5 model, error as bellow

### ISSUE THREAD

**Issue by jasoncow007** [kijai/ComfyUI-Florence2#79]
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Florence2\nodes.py", line 97, in loadmodel
    model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation=attention, device_map=device, torch_dtype=dtype,trust_remote_code=True)
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\transformers\models\auto\auto_factory.py", line 526, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1025, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `florence2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

**Comment by Jeff-goal** [comment]
same problem, even after reinstalled the plugin

**Comment by askmyteapot** [comment]
So its an issue with the promptgen model's config file. 

I got it to work by doing the following. 
1) Edit config.json and add in the following at line 6
```  "auto_map": {
  "AutoConfig": "configuration_florence2.Florence2Config",
  "AutoModelForCausalLM": "modeling_florence2.Florence2ForConditionalGeneration"
  },
```
2) Copy from the folder `florence2_large` subfolder the 3 *_florence2.py files into the main folder for promtgen 

It will re-download a newer file from the microsoft repo, then it will work. 

![image](https://github.com/user-attachments/assets/7cf916cb-1814-4cec-9ffb-f13f3ea4b7e9)
![image](https://github.com/user-attachments/assets/df2983a3-e9d8-44b1-ab76-ff39125322b1)

**Comment by freshwind-bit** [comment]
@askmyteapot A small clarification for your instruction "Edit config.json and add the following to line 6":
not add to line 6, but insert before line 6. For a large 1.5 model it should look like this:
`{
  "_name_or_path": "microsoft/Florence-2-large",
  "architectures": [
    "Florence2ForConditionalGeneration"
  ],
  "auto_map": {
    "AutoConfig": "configuration_florence2.Florence2Config",
    "AutoModelForCausalLM": "modeling_florence2.Florence2ForConditionalGeneration"
  },  
  "bos_token_id": 0,
  "eos_token_id": 2,`
Accordingly, for the basic 1.5 model it should look like this:
`{
  "_name_or_path": "microsoft/Florence-2-base-ft",
  "architectures": [
    "Florence2ForConditionalGeneration"
  ],
  "auto_map": {
    "AutoConfig": "configuration_florence2.Florence2Config",
    "AutoModelForCausalLM": "modeling_florence2.Florence2ForConditionalGeneration"
  },  
  "bos_token_id": 0
  "eos_token_id": 2,`

**Comment by 2d2d1** [comment]
我怎么看不懂，哪里有编辑config.json并在第 6 行添加以下内容
