### ISSUE TITLE
LoadFlorence2Model error

### ISSUE THREAD

**Issue by ql0wn4** [kijai/ComfyUI-Florence2#85]
# ComfyUI Error Report
## Error Details
- **Node Type:** LoadFlorence2Model
- **Exception Type:** ValueError
- **Exception Message:** list.remove(x): x not in list
## Stack Trace
```
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 148, in load
    self.model, self.processor = load_model(version, self.device)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 40, in load_model
    model = AutoModelForCausalLM.from_pretrained(identifier, cache_dir=comfy_model_dir, trust_remote_code=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 540, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 365, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 181, in check_imports
    imports = get_imports(filename)
              ^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 29, in fixed_get_imports
    imports.remove("flash_attn")

```
## System Information
- **ComfyUI Version:** v0.2.3-5-g3c60ecd
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 11609833472
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-10-14 10:58:13,205 - root - INFO - Total VRAM 12288 MB, total RAM 32682 MB
2024-10-14 10:58:13,205 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-14 10:58:13,206 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-14 10:58:13,206 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
2024-10-14 10:58:15,882 - root - INFO - Using pytorch cross attention
2024-10-14 10:58:18,778 - root - INFO - [Prompt Server] web root: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\web
2024-10-14 10:58:32,954 - root - INFO - Total VRAM 12288 MB, total RAM 32682 MB
2024-10-14 10:58:32,955 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-14 10:58:32,957 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-14 10:58:32,957 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
2024-10-14 10:58:41,757 - root - INFO - 
Import times for custom nodes:
2024-10-14 10:58:41,757 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-14 10:58:41,757 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-14 10:58:41,757 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-10-14 10:58:41,757 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
2024-10-14 10:58:41,757 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_Noise
2024-10-14 10:58:41,757 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-14 10:58:41,757 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\sd-dynamic-thresholding
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\masquerade-nodes-comfyui
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\comfyui-tooling-nodes
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\DJZ-Nodes
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyMath
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\comfyui-various
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\x-flux-comfyui
2024-10-14 10:58:41,758 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-14 10:58:41,759 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-14 10:58:41,759 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\rgthree-comfy
2024-10-14 10:58:41,759 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_ExtraModels
2024-10-14 10:58:41,759 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-14 10:58:41,759 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2024-10-14 10:58:41,759 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-10-14 10:58:41,759 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper
2024-10-14 10:58:41,759 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-14 10:58:41,759 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyI2I
2024-10-14 10:58:41,759 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\PuLID_ComfyUI
2024-10-14 10:58:41,759 - root - INFO -    0.2 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\comfyui-reactor-node
2024-10-14 10:58:41,759 - root - INFO -    0.3 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\comfyui-tensorops
2024-10-14 10:58:41,760 - root - INFO -    0.6 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-14 10:58:41,760 - root - INFO -    0.7 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-10-14 10:58:41,760 - root - INFO -    1.3 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-10-14 10:58:41,760 - root - INFO -    1.9 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\comfyui-art-venture
2024-10-14 10:58:41,760 - root - INFO -    2.5 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux
2024-10-14 10:58:41,760 - root - INFO -    3.7 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-14 10:58:41,760 - root - INFO -    8.8 seconds: E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-10-14 10:58:41,760 - root - INFO - 
2024-10-14 10:58:41,774 - root - INFO - Starting server

2024-10-14 10:58:41,774 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-14 11:01:55,019 - root - INFO - got prompt
2024-10-14 11:01:55,533 - root - INFO - Using pytorch attention in VAE
2024-10-14 11:01:55,534 - root - INFO - Using pytorch attention in VAE
2024-10-14 11:01:57,272 - root - ERROR - !!! Exception during processing !!! list.remove(x): x not in list
2024-10-14 11:01:57,279 - root - ERROR - Traceback (most recent call last):
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 148, in load
    self.model, self.processor = load_model(version, self.device)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 40, in load_model
    model = AutoModelForCausalLM.from_pretrained(identifier, cache_dir=comfy_model_dir, trust_remote_code=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 540, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 365, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 181, in check_imports
    imports = get_imports(filename)
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 29, in fixed_get_imports
    imports.remove("flash_attn")
ValueError: list.remove(x): x not in list

2024-10-14 11:01:57,281 - root - INFO - Prompt executed in 2.07 seconds
2024-10-14 11:17:20,532 - root - INFO - got prompt
2024-10-14 11:17:21,961 - root - ERROR - !!! Exception during processing !!! list.remove(x): x not in list
2024-10-14 11:17:21,962 - root - ERROR - Traceback (most recent call last):
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 148, in load
    self.model, self.processor = load_model(version, self.device)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 40, in load_model
    model = AutoModelForCausalLM.from_pretrained(identifier, cache_dir=comfy_model_dir, trust_remote_code=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 540, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 365, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 181, in check_imports
    imports = get_imports(filename)
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 29, in fixed_get_imports
    imports.remove("flash_attn")
ValueError: list.remove(x): x not in list

2024-10-14 11:17:21,963 - root - INFO - Prompt executed in 1.24 seconds
2024-10-14 11:20:03,995 - root - INFO - got prompt
2024-10-14 11:20:05,278 - root - ERROR - !!! Exception during processing !!! list.remove(x): x not in list
2024-10-14 11:20:05,280 - root - ERROR - Traceback (most recent call last):
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 148, in load
    self.model, self.processor = load_model(version, self.device)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 40, in load_model
    model = AutoModelForCausalLM.from_pretrained(identifier, cache_dir=comfy_model_dir, trust_remote_code=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 540, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 365, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 181, in check_imports
    imports = get_imports(filename)
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 29, in fixed_get_imports
    imports.remove("flash_attn")
ValueError: list.remove(x): x not in list

2024-10-14 11:20:05,281 - root - INFO - Prompt executed in 1.12 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
[LoadFlorence2Model error.json](https://github.com/user-attachments/files/17362766/LoadFlorence2Model.error.json)

**Comment by kijai** [comment]
You are not using my nodes, that error comes from using these nodes: https://github.com/spacepxl/ComfyUI-Florence-2

**Comment by ADaNiu123** [comment]
Downloading Florence2 model to: D:\SD\ComfyUI-aki-v1.2\models\LLM\Florence-2-base
!!! Exception during processing !!! (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/microsoft/Florence-2-base/revision/main (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))"), '(Request ID: 06d084e5-c1f4-4a43-afef-a7325186054e)')
